### ISSUE TITLE
Unexpected return values and process exits after Python worker timeout

### ISSUE THREAD

**Issue by specv** [RustySnek/Venomous#24]
After a Python function call times out, subsequent calls behave unexpectedly:

1. When a Python function call times out, it correctly returns a timeout error.
2. The next call to a Python function returns an `%ErlangError{original: :stopped, reason: nil}`.
3. Any further attempts to call a Python function cause the current process to exit.

To reproduce this issue, you can use the following code:

``` Elixir
import ExUnit.Assertions
import Venomous
import Venomous.SnakeArgs

# First call: Timeout
assert from_params(:time, :sleep, [2])
       |> python(python_timeout: 1000) ==
         %{error: :timeout}

# Second call: ErlangError
assert from_params(:operator, :add, [1, 1]) |> python() ==
         %ErlangError{original: :stopped, reason: nil}

# Third call: Process exit
assert catch_exit(
         from_params(:operator, :add, [1, 1])
         |> python()
       ) == :normal
```

**Comment by RustySnek** [comment]
Pretty crazy ngl. I remember finding it myself and kind of forgetting about it. The issue was multiple things.
First was that I used Task.run() which wouldn't really get terminated alongside the genserver
Second was that it was sometimes capturing exit signal from the Port that was killed alongside python process.
Third was that sometimes before the genserver got killed, it returned the ErlangError that indicates that the erlport python process was stopped.

Should be fixed with #25 
I will probably release it with the #23 once im done with it
Thanks for the report 😄
